# Generated by Django 4.0 on 2022-02-08 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caja', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000000000)])),
            ],
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sede_caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.caja')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sede')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_sede_caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_sede_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sede_caja')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('priodidad', models.BooleanField()),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_sede_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sede_caja')),
            ],
        ),
        migrations.CreateModel(
            name='atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
                ('id_sede_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sede_caja')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.turno')),
            ],
        ),
    ]
