# Generated by Django 4.0 on 2022-02-12 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(10000000000000)]),
        ),
    ]
