# Generated by Django 4.0 on 2022-02-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_caja_numero_caja_alter_cliente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='turno',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.cliente'),
        ),
    ]
