# Generated by Django 4.0 on 2022-02-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_usuario_sede_caja_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_sede_caja',
            name='id_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.usuario'),
        ),
    ]
