# Generated by Django 4.0 on 2022-02-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_usuario_sede_caja_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='id_sede_caja',
        ),
    ]
