# Generated by Django 4.0 on 2022-02-21 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_turno_id_sede_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
