# Generated by Django 4.0 on 2022-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_atencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
