# Generated by Django 4.0 on 2022-02-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_atencion_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='priodidad',
            new_name='prioridad',
        ),
    ]
